### ISSUE TITLE
only one image

### ISSUE THREAD

**Issue by empdigitalcl** [peremp/vue-light-gallery#5] opened 2019-05-02 16:35 UTC
Hi, this not work only one image on array? like this:

images: [
 { title:'img 1', url: 'path/to/image_1.jpg' },
],

**Comment by peremp** [comment] 2019-05-02 16:45
Yes, it works.
Are you having issues?

**Comment by empdigitalcl** [comment] 2019-05-02 17:51
Yeah, show the loading view, when put  the array whit more one image works

**Comment by peremp** [comment] 2019-05-09 10:02
It's working fine.
Here a working example: https://codepen.io/peremp/pen/mYVOZm

**Comment by peremp** [comment] 2019-05-13 08:28
since it cannot be reproduced and looks like it works properly I close the issue.

**Closed by peremp** 2019-05-13 08:28 UTC
